plugins {
    id 'java-library'
}

group = 'org.momo'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':Common')
    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    runtimeOnly 'com.mysql:mysql-connector-j'
}

test {
    useJUnitPlatform()
}
